apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-client
  namespace: spiffe-client-ns
  labels:
    app: spiffe-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-client
  template:
    metadata:
      labels:
        app: spiffe-client
    spec:
      serviceAccountName: spiffe-client-sa
      containers:
      - name: spiffe-client
        image: semenyukandriyv/spiffe-client:latest
        imagePullPolicy: IfNotPresent

        # Mount the SPIRE agent socket so the Go application can request its SPIFFE SVID
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true

        # Environment variable for Go app to know where the socket is
        env:
        - name: TZ
          value: "America/New_York"
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/spire-agent.sock"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      # Use SPIFFE CSI Driver to provide the SPIRE Workload API socket
      volumes:
      - name: spire-agent-socket
        csi:
          driver: csi.spiffe.io
          readOnly: true